#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env.local"
DATA_SQL="$ROOT_DIR/src/main/resources/data.sql"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

require_env() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "Missing required env: $name" >&2
    exit 1
  fi
}

require_env DB_HOST
require_env DB_PORT
require_env DB_NAME
require_env DB_USER
require_env DB_PASSWORD

mysql_exec() {
  MYSQL_PWD="$DB_PASSWORD" mysql \
    --protocol=TCP \
    -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" \
    --batch --skip-column-names \
    "$DB_NAME" \
    -e "$1"
}

mysqldump_exec() {
  MYSQL_PWD="$DB_PASSWORD" mysqldump \
    --protocol=TCP \
    -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" \
    --no-create-info \
    --skip-triggers \
    --skip-comments \
    --set-gtid-purged=OFF \
    --column-statistics=0 \
    --complete-insert \
    --extended-insert=FALSE \
    "$DB_NAME" \
    "$@"
}

die() {
  echo "Error: $1" >&2
  exit 1
}

table_exists() {
  local table="$1"
  [[ -n "$(mysql_exec "SHOW TABLES LIKE '${table}';")" ]]
}

column_exists() {
  local table="$1"
  local column="$2"
  [[ -n "$(mysql_exec "SHOW COLUMNS FROM \`${table}\` LIKE '${column}';")" ]]
}

detect_account_table() {
  local candidates=(accounts users users_info member user)
  local table
  for table in "${candidates[@]}"; do
    if table_exists "$table"; then
      echo "$table"
      return 0
    fi
  done
  return 1
}

sql_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\'/\\\'}"
  printf '%s' "$value"
}

write_base() {
  table_exists store || die "store table not found"
  table_exists admin_profiles || die "admin_profiles table not found"

  tmp_file="$(mktemp)"
  {
    echo "-- generated by scripts/seed_dump.sh"
    echo "SET FOREIGN_KEY_CHECKS=0;"
    echo "-- SECTION: store"
    mysqldump_exec store
    echo "-- SECTION: account"
    echo "-- SECTION: admin_profiles"
    mysqldump_exec admin_profiles
    echo "SET FOREIGN_KEY_CHECKS=1;"
  } > "$tmp_file"

  mv "$tmp_file" "$DATA_SQL"
  echo "Wrote $DATA_SQL"
}

insert_after_marker() {
  local marker="$1"
  local insert_file="$2"

  if [[ ! -s "$insert_file" ]]; then
    return 0
  fi

  python3 - "$DATA_SQL" "$marker" "$insert_file" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
marker = sys.argv[2]
insert_path = Path(sys.argv[3])

text = path.read_text()
insert = insert_path.read_text().rstrip()
if not insert:
    sys.exit(0)

idx = text.find(marker)
if idx == -1:
    raise SystemExit(f"Marker not found: {marker}")

line_end = text.find("\n", idx)
if line_end == -1:
    line_end = len(text)

new_text = text[: line_end + 1] + insert + "\n" + text[line_end + 1 :]
path.write_text(new_text)
PY
}

append_user() {
  local email="${1:-}"
  local user_id="${2:-}"
  local account_table
  local where

  account_table="$(detect_account_table)" || die "No account-like table found"

  if [[ -n "$email" ]]; then
    if column_exists "$account_table" email; then
      where="email='$(sql_escape "$email")'"
    elif column_exists "$account_table" user_id; then
      where="user_id='$(sql_escape "$email")'"
    else
      die "No email or user_id column found in $account_table"
    fi
  else
    if column_exists "$account_table" user_id; then
      where="user_id='$(sql_escape "$user_id")'"
    elif column_exists "$account_table" email; then
      where="email='$(sql_escape "$user_id")'"
    else
      die "No user_id or email column found in $account_table"
    fi
  fi

  local count
  count="$(mysql_exec "SELECT COUNT(*) FROM \`${account_table}\` WHERE ${where};")"
  if [[ "$count" -eq 0 ]]; then
    die "No row found in ${account_table} for ${where}"
  fi

  if ! column_exists "$account_table" id; then
    die "id column not found in ${account_table}"
  fi

  local account_id
  account_id="$(mysql_exec "SELECT id FROM \`${account_table}\` WHERE ${where} LIMIT 1;")"
  if [[ -z "$account_id" ]]; then
    die "Failed to resolve account id"
  fi

  [[ -f "$DATA_SQL" ]] || die "${DATA_SQL} not found. Run './scripts/seed_dump.sh base' first."

  local account_dump
  local admin_dump
  account_dump="$(mktemp)"
  admin_dump="$(mktemp)"

  mysqldump_exec "$account_table" --where="${where}" > "$account_dump"

  if table_exists admin_profiles && column_exists admin_profiles account_id; then
    local admin_count
    admin_count="$(mysql_exec "SELECT COUNT(*) FROM admin_profiles WHERE account_id=${account_id};")"
    if [[ "$admin_count" -gt 0 ]]; then
      mysqldump_exec admin_profiles --where="account_id=${account_id}" > "$admin_dump"
    fi
  fi

  insert_after_marker "-- SECTION: account" "$account_dump"
  insert_after_marker "-- SECTION: admin_profiles" "$admin_dump"

  rm -f "$account_dump" "$admin_dump"

  echo "Appended ${account_table} (id=${account_id}) to $DATA_SQL"
}

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/seed_dump.sh base
  ./scripts/seed_dump.sh user --email you@example.com
  ./scripts/seed_dump.sh user --user-id your_user_id
USAGE
}

mode="${1:-}"
shift || true

case "$mode" in
  base)
    write_base
    ;;
  user)
    email=""
    user_id=""
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --email)
          email="${2:-}"
          shift 2
          ;;
        --user-id|--user_id|--userid)
          user_id="${2:-}"
          shift 2
          ;;
        *)
          die "Unknown argument: $1"
          ;;
      esac
    done

    if [[ -z "$email" && -z "$user_id" ]]; then
      die "Provide --email or --user-id"
    fi

    append_user "$email" "$user_id"
    ;;
  *)
    usage
    exit 1
    ;;
esac
